<?php

/**
 * BaseProjectHasTeamMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $team_member_id
 * @property Project $Project
 * @property TeamMember $TeamMember
 * 
 * @method integer              getProjectId()      Returns the current record's "project_id" value
 * @method integer              getTeamMemberId()   Returns the current record's "team_member_id" value
 * @method Project              getProject()        Returns the current record's "Project" value
 * @method TeamMember           getTeamMember()     Returns the current record's "TeamMember" value
 * @method ProjectHasTeamMember setProjectId()      Sets the current record's "project_id" value
 * @method ProjectHasTeamMember setTeamMemberId()   Sets the current record's "team_member_id" value
 * @method ProjectHasTeamMember setProject()        Sets the current record's "Project" value
 * @method ProjectHasTeamMember setTeamMember()     Sets the current record's "TeamMember" value
 * 
 * @package    Domain Checker
 * @subpackage model
 * @author     Dave Walker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectHasTeamMember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_has_team_member');
        $this->hasColumn('project_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('team_member_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_project_has_team_member_team_member1', array(
             'fields' => 
             array(
              0 => 'team_member_id',
             ),
             ));
        $this->index('fk_project_has_team_member_project1', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'no action'));

        $this->hasOne('TeamMember', array(
             'local' => 'team_member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'no action'));
    }
}