<?php

/**
 * BaseCheck
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $status
 * @property timestamp $created
 * @property integer $project_id
 * @property Project $Project
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getStatus()     Returns the current record's "status" value
 * @method timestamp getCreated()    Returns the current record's "created" value
 * @method integer   getProjectId()  Returns the current record's "project_id" value
 * @method Project   getProject()    Returns the current record's "Project" value
 * @method Check     setId()         Sets the current record's "id" value
 * @method Check     setStatus()     Sets the current record's "status" value
 * @method Check     setCreated()    Sets the current record's "created" value
 * @method Check     setProjectId()  Sets the current record's "project_id" value
 * @method Check     setProject()    Sets the current record's "Project" value
 * 
 * @package    Domain Checker
 * @subpackage model
 * @author     Dave Walker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCheck extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('checks');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('created', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('project_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_checks_project1', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'no action'));
    }
}