<?php

/**
 * BaseClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Projects
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getTitle()    Returns the current record's "title" value
 * @method Doctrine_Collection getProjects() Returns the current record's "Projects" collection
 * @method Client              setId()       Sets the current record's "id" value
 * @method Client              setTitle()    Sets the current record's "title" value
 * @method Client              setProjects() Sets the current record's "Projects" collection
 * 
 * @package    Domain Checker
 * @subpackage model
 * @author     Dave Walker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));

        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project as Projects', array(
             'local' => 'id',
             'foreign' => 'client_id'));
    }
}