<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $domain
 * @property integer $client_id
 * @property Client $Client
 * @property Doctrine_Collection $ProjectTeam
 * @property Doctrine_Collection $Checks
 * @property Doctrine_Collection $ProjectHasTeamMembers
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getDomain()                Returns the current record's "domain" value
 * @method integer             getClientId()              Returns the current record's "client_id" value
 * @method Client              getClient()                Returns the current record's "Client" value
 * @method Doctrine_Collection getProjectTeam()           Returns the current record's "ProjectTeam" collection
 * @method Doctrine_Collection getChecks()                Returns the current record's "Checks" collection
 * @method Doctrine_Collection getProjectHasTeamMembers() Returns the current record's "ProjectHasTeamMembers" collection
 * @method Project             setId()                    Sets the current record's "id" value
 * @method Project             setDomain()                Sets the current record's "domain" value
 * @method Project             setClientId()              Sets the current record's "client_id" value
 * @method Project             setClient()                Sets the current record's "Client" value
 * @method Project             setProjectTeam()           Sets the current record's "ProjectTeam" collection
 * @method Project             setChecks()                Sets the current record's "Checks" collection
 * @method Project             setProjectHasTeamMembers() Sets the current record's "ProjectHasTeamMembers" collection
 * 
 * @package    Domain Checker
 * @subpackage model
 * @author     Dave Walker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('domain', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('client_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_project_client', array(
             'fields' => 
             array(
              0 => 'client_id',
             ),
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'no action'));

        $this->hasMany('TeamMember as ProjectTeam', array(
             'refClass' => 'ProjectHasTeamMember',
             'local' => 'project_id',
             'foreign' => 'team_member_id'));

        $this->hasMany('Check as Checks', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $this->hasMany('ProjectHasTeamMember as ProjectHasTeamMembers', array(
             'local' => 'id',
             'foreign' => 'project_id'));
    }
}