<?php

/**
 * Project
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Domain Checker
 * @subpackage model
 * @author     Dave Walker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Project extends BaseProject
{
  public function __toString()
  {
    return $this->getDomain();
  }

  public function getStatus()
  {
    $ch = curl_init($this->getDomain());
    curl_setopt($ch, CURLOPT_NOBODY, 1);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);

    $result = curl_exec($ch);

    $status = $result ? "OK" : "ERROR";

    // add a record of this domain check to our DB
    $check = new Check();
    $check->setStatus($status);
    $check->setProjectId($this->getId());
    $check->setCreated(date("Y-m-d h:i:s"));
    $check->save();

    return $status;
  }

  public function getStatusCode()
  {
    return $this->getStatus() == "OK" ? "ok" : "remove";
  }

  public function getStatusColor()
  {
    return $this->getStatus() == "OK" ? "success" : "danger";
  }
}