# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

homepage:
  url:   /
  param: { module: HomePage, action: index }

check_domain:
  url:   /check-domain/
  param: { module: HomePage, action: checkDomain }

check_count:
  url:   /check-count/
  param: { module: HomePage, action: checkCount }

ping_domains:
  url:   /ping-domains/
  param: { module: HomePage, action: pingDomains }
  

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
