generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TeamMember
    theme:                 cp
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          team_member
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, email, telephone]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
