<?php

/**
 * BasePath
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $template_type
 * @property integer $object_id
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method string  getTemplateType()  Returns the current record's "template_type" value
 * @method integer getObjectId()      Returns the current record's "object_id" value
 * @method Path    setId()            Sets the current record's "id" value
 * @method Path    setTemplateType()  Sets the current record's "template_type" value
 * @method Path    setObjectId()      Sets the current record's "object_id" value
 * 
 * @package    Domain Checker
 * @subpackage model
 * @author     Dave Walker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePath extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('path');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('template_type', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $lockable0 = new Doctrine_Template_Lockable();
        $metadatable0 = new Doctrine_Template_Metadatable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($lockable0);
        $this->actAs($metadatable0);
        $this->actAs($nestedset0);
    }
}