<?php

/**
 * PluginPathTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPathTable extends Doctrine_Table
{
 	public function getFormattedTemplateType ($type = null)
    {
       // TODO: fix me

       if (empty($type))
       {
           $type = sfContext::getInstance()->getRequest()->getParameter("type", "ContentPage");
       }
       while ($type != $y = preg_replace("/([a-z])([A-Z][a-z]+)/", "$1 $2", $type))
       {
         $type = $y;
       }

       return $type;
    }
  	public static function retrieveTree()
  	{
    	return self::getInstance()->getNode()->fetchTree();
  	}
    public function getHomepage($homePageTemplate = null)
    {
      $query = $this->createQuery("p")->where("level = ?", 0);

      if ($homePageTemplate || $homePageTemplate = sfConfig::get('app_cms_routing_homepage_template'))
      {
        $query->addWhere("template_type = ?", $homePageTemplate);
      }

      return $query->fetchOne()->getObject();
    }
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPathTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPath');
    }
}
